### ISSUE TITLE
File/Folder ignore filter

### ISSUE THREAD

**Issue by SimonNitzsche** [LUDevNet/LUpdate#2]
Ignore folders and files like the .git directory or the project config

**Comment by Xiphoseer** [comment]
I assume you mean for the cache command? I can add a filter, sure.

**Comment by SimonNitzsche** [comment]
More specifically for the trunk.txt for the cache.

**Comment by Xiphoseer** [comment]
> More specifically for the trunk.txt for the cache.

Right now, if it's in trunk, it's delivered as sd0, granted its difficult to find them if you don't have them already and can hash them.

**Comment by Xiphoseer** [comment]
You can now optionally specify `include` and `exclude` as lists of globs for files in each project which will be considered when caching files. I'll close the issue for now, please file a new one if you need additional CLI flags.
