### ISSUE TITLE
Cap speed for spinning wheel

### ISSUE THREAD

**Issue by SimonNitzsche** [LUDevNet/LUpdate#3]
It makes sense to spin it slower if stuff takes longer, however there seems to be no maximum speed for the spinning wheel in the console.

**Comment by Xiphoseer** [comment]
I think that's just a visual thing. The spinner icon has a built-in limited refresh rate for when it actually re-draws, but updates the spinner state after every file, so it just looks a little to fast

**Comment by Xiphoseer** [comment]
Spinning wheel has been removed completely
