### ISSUE TITLE
Configurable output project name.

### ISSUE THREAD

**Issue by SimonNitzsche** [LUDevNet/LUpdate#4]
Currently the base directory within the trunk.txt is `[project.foo].dir` starting from `[general].src`

Assuming following file structure:

```
build
    - main
        - client
    - test
        - client
LUpdate.toml
```

it will result into putting following paths into the `trunk.txt`
```
main/client\boot.cfg,761,b9c2d8f6145ce866e78bb3ea53d028ba,398,72626d079a74d9795902215df53cf663,0e5f69c1055f166128bcb96c9e2d7b0c
```

while we would want something like
```
client\boot.cfg,761,b9c2d8f6145ce866e78bb3ea53d028ba,398,72626d079a74d9795902215df53cf663,0e5f69c1055f166128bcb96c9e2d7b0c
```

**Comment by Xiphoseer** [comment]
Completed in 8187ff43, there now is a per-project `prefix` you can set (e.g. `client`) that will be used. The default is now the last component of `dir` i.e. the path to the project root.
