### ISSUE TITLE
Quickcheck configuration file

### ISSUE THREAD

**Issue by SimonNitzsche** [LUDevNet/LUpdate#5]
Allow use of an configuration file to flag specific files for quickcheck.

Why?
Currently each file is checked for modification by validating a filehash. When it is possible to flag certain files (that we know are not changed) as quickcheck those files are not validated by its file content but only by its existance (Also make use of an existing trunk.txt). This would result into much faster speeds for warm-builds.

**Comment by Xiphoseer** [comment]
If the filestamps don't change, I'd prefer sth like the actual "quickcheck.txt" from the patcher, which skips a file if the last modified time on a file hasn't changed

**Comment by Xiphoseer** [comment]
Closed by 4717cec and the `-F` flag
